name: Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: diconais
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: none

      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock', '**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Wait for MySQL to be ready
        run: until mysqladmin ping -h 127.0.0.1 --silent; do sleep 1; done

      - name: Set up test database schema
        run: |
          php bin/console doctrine:migrations:migrate --env=test --no-interaction

      - name: Build SASS assets
        run: php bin/console sass:build

      - name: Install importmap assets
        run: php bin/console importmap:install

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DATABASE_URL: "mysql://root@127.0.0.1:3306/diconais?serverVersion=8.0.32&charset=utf8mb4"
        run: vendor/bin/phpunit --testdox
